name: workshop-env
channels:
  - conda-forge
dependencies:
  - python=3.12.10
  - gdal<=3.10.2
  - imagecodecs
  - ipywidgets
  - jupyterlab
  - leafmap
  - geopandas
  - rasterio
  - rasterstats
  - pdal=2.8.4
  - trimesh
  
  - pip
  - pip:
    - pystac-client
    - mapbox-earcut
    - triangle
    - manifold3d

 
