# site_name: DGI - Workshop
# theme: readthedocs
# nav:
#   - Home: index.md
#   - Setup: setup/index.md
#         - Google Colab: setup/Google Colab/index.md
#         - Local environment: setup/Local Environment/index.md
#   - Contact: contact.md



site_name: DGI - Workshop
theme: readthedocs
nav:
  - Home: index.md
  - Setup: 
    - Overview: setup/index.md
    - Fork the Repo: setup/fork-repo/index.md
    - MyBinder: setup/mybinder/index.md
    - Google Colab: setup/google-colab/index.md
    - Local environment: setup/local-environment/index.md
  - Contact: contact.md