site_name: DGI - Workshop
theme: readthedocs
nav:
  - Home: index.md
  - Environment: 
    - Overview: setup/index.md
    - Fork the Repo: setup/fork-repo/index.md
    # - MyBinder: setup/mybinder/index.md
    - Local environment: setup/local-environment/index.md
  - SpatioTemporal Asset Catalog:
    - STAC: stac/stac/index.md
  
  - Contact: contact.md