site_name: DGI - Workshop
theme: readthedocs 
nav:
  - Home: index.md
  - Environment: environment/index.md
  - SpatioTemporal Asset Catalog:
    - STAC: stac/stac/index.md
    - Stac-Browser: stac/stac-browser/index.md
  
  - Contact: contact.md