site_name: DGI - Workshop
theme: readthedocs 
nav:
  - Home: index.md
  - Contact: contact.md
  - Resources: resources/index.md
  - SpatioTemporal Asset Catalog:
    - STAC: stac/stac/index.md
    - Stac-Browser: stac/stac-browser/index.md
  - STAC with Desktop GIS: 
    - QGIS: desktop-gis/qgis/index.md
    - ArcGIS Pro: desktop-gis/arcgis-pro/index.md  
  - Python: 
    - Exercises: python/index.md
  - Environment (Optional): 
    - Setup: environment/index.md
    - MyBinder: environment/mybinder/index.md
extra:
  version: 0.0.5